import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/navbar/nav-comp";
import Footer from "@/components/footer/footer-comp";
import Provider from "@/provider/provider";
import {
  Inter,
  Montserrat,
  Oxanium,
  Work_Sans,
  Poppins,
} from "next/font/google";

export const metadata = {
  title: "Nabil's Porto",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["400", "600", "700"],
});
const oxanium = Oxanium({
  subsets: ["latin"],
  variable: "--oxanium",
  weight: ["400", "600", "700"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`h-screen ${oxanium.className} mx-auto w-10/12 flex flex-col bg-white dark:bg-black`}
        >
          <Navbar />

          <main className="flex flex-col    flex-1 max-w-6xl w-full  ">
            {children}
            <Footer />
          </main>
        </body>
      </Provider>
    </html>
  );
}
